import {get} from "lodash";
import internalServerError from "@framework/helpers/internalServerError.js";
import Model from "@framework/model/model.js";


class {{controllerName name}} extends Model {
	
	constructor() {
		super({
			tableName: "{{ name }}"
		})
	}

	async {{ controllerName name }}View(_, args) {
		try {
			const {id} = args;
			let find = await this.model.findByPk(id);
			if (find) {
				find.successMessageType = "Success";
				find.successMessage = "Item fetched";
				return find;
			}else {
				return {
					errorMessageType: "{{controllerName name}} not found", 
					errorMessage: "{{controllerName name}} not found, please try again",
					statusCode: 'NOT_FOUND'
				}
			}
		} catch (e) {
			return internalServerError(e);
		}
	}
	async {{ controllerName name }}Create(_, args) {
		try {
			let create = await this.create(args);
			let {instance} = create;
			if (instance) {
				instance.statusCode = "CREATED";
				instance.successMessageType = "Created";
				instance.successMessage = "{{controllerName name}} created successfully";
				return instance;
			}else {
				return internalServerError({message: "Something went wrong"});
			}
		} catch (e) {
			return internalServerError(e);
		}
	}
	async {{ controllerName name }}Update(_, args) {
		try {
			const {id} = args;
			let update =  await this.model.findOne(id).update(args);
			update.successMessageType = "Updated";
			update.successMessage = "{{ controllerName name }} updated successfully";
			return update;
		} catch (e) {
			return internalServerError(e);
		}
	}
	async {{ controllerName name }}List(_, args) {
		try {

		} catch (e) {
			return internalServerError(e);
		}
	}

}


export default new {{controllerName name}}();